-- 코드를 작성해주세요
# SELECT ROUND(SUM(LENGTH)/COUNT(*), 2) AS AVERAGE_LENGTH
# FROM FISH_INFO
# WHERE NOT ISNULL(LENGTH);

SELECT ROUND(AVG(
        CASE 
            WHEN ISNULL(LENGTH) THEN 10
            ELSE LENGTH
        END),2) AS AVERAGE_LENGTH
FROM FISH_INFO