-- 코드를 입력하세요
-- SELECT *
-- FROM USED_GOODS_USER UGU
-- JOIN USED_GOODS_BOARD UGB ON UGB.WRITER_ID = UGU.USER_ID

-- SELECT 
-- FROM USED_GOODS_USER

SELECT UGD.USER_ID, UGD.NICKNAME, (UGD.CITY || ' ' || UGD.STREET_ADDRESS1 || ' ' || UGD.STREET_ADDRESS2) AS 전체주소,
        CASE WHEN LENGTH(TLNO) = 11
             THEN SUBSTR(UGD.TLNO,0,3) || '-' ||SUBSTR(UGD.TLNO,4,4) || '-' || SUBSTR(UGD.TLNO,8,4) 
             END AS 전화번호
FROM USED_GOODS_USER UGD
WHERE UGD.USER_ID IN (SELECT WRITER_ID
                    FROM USED_GOODS_BOARD UGB
                    GROUP BY WRITER_ID
                    HAVING COUNT(WRITER_ID) >= 3)
ORDER BY UGD.USER_ID DESC
