-- 코드를 입력하세요

SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS OUTS
,(SELECT INS.ANIMAL_ID
FROM ANIMAL_INS INS
WHERE INS.SEX_UPON_INTAKE LIKE '%Intact%') INS
WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID AND (OUTS.SEX_UPON_OUTCOME LIKE '%Spayed%' OR OUTS.SEX_UPON_OUTCOME LIKE '%Neutered%')
