-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(SUM(RR.REVIEW_SCORE) / COUNT(RI.REST_ID), 2) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR on RR.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC;
