-- 코드를 입력하세요
-- SELECT *
-- FROM USER_INFO U
-- INNER JOIN ONLINE_SALE OS ON OS.USER_ID = U.USER_ID


SELECT EXTRACT(YEAR FROM OS.SALES_DATE) as YEAR, EXTRACT(MONTH FROM OS.SALES_DATE) as MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) as USERS
FROM USER_INFO U
INNER JOIN ONLINE_SALE OS ON OS.USER_ID = U.USER_ID
WHERE U.GENDER >= 0
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), EXTRACT(MONTH FROM OS.SALES_DATE), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER