-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
WHERE NOT EXISTS (SELECT INS.ANIMAL_ID 
              FROM ANIMAL_INS INS
              WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID)
ORDER BY OUTS.ANIMAL_ID