-- 코드를 입력하세요
WITH SELL_DATA AS 
(SELECT OS.ONLINE_SALE_ID, OS.USER_ID, OS.PRODUCT_ID, OS.SALES_AMOUNT, OS.SALES_DATE
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE YEAR(JOINED) = '2021')

SELECT YEAR(SD.SALES_DATE) AS YEAR, MONTH(SD.SALES_DATE) AS MONTH, COUNT(DISTINCT SD.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT SD.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PURCHASED_RATIO
FROM SELL_DATA SD
GROUP BY YEAR(SD.SALES_DATE), MONTH(SD.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;