-- 코드를 입력하세요
SELECT CAR_ID, CASE WHEN CAR_ID IN
                    (SELECT C2.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
                     WHERE '2022-10-16' BETWEEN C2.START_DATE AND C2.END_DATE)
                     THEN '대여중' ELSE '대여 가능'
                     END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
GROUP BY C1.CAR_ID
ORDER BY C1.CAR_ID DESC;