-- 코드를 입력하세요
SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS
WHERE NOT EXISTS(SELECT OUTS.ANIMAL_ID
                FROM ANIMAL_OUTS OUTS
                WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID) 
-- AND ROWNUM <= 3
ORDER BY INS.DATETIME
FETCH FIRST 3 ROWS ONLY;