-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP, (SELECT FO.PRODUCT_ID, FO.AMOUNT
                      FROM FOOD_ORDER FO
                      WHERE EXTRACT(MONTH FROM FO.produce_date) = 5) FO
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID