-- 코드를 입력하세요
SELECT ICECREAM.FLAVOR
FROM (SELECT FH.FLAVOR, FH.TOTAL_ORDER
      FROM FIRST_HALF FH
      UNION ALL
      SELECT J.FLAVOR, J.TOTAL_ORDER
      FROM JULY J) AS ICECREAM
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;