-- 코드를 입력하세요

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID = 
(SELECT RR.MEMBER_ID
FROM (SELECT RR.MEMBER_ID, COUNT(RR.MEMBER_ID) AS CM
            FROM REST_REVIEW RR
            GROUP BY RR.MEMBER_ID
            ORDER BY CM DESC) RR
WHERE ROWNUM <= 1)
ORDER BY RR.REVIEW_DATE, REVIEW_TEXT