-- 코드를 입력하세요
WITH REVIEW AS (SELECT COUNT(*) AS COUNT
                FROM MEMBER_PROFILE MP
                JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
                GROUP BY MP.MEMBER_ID
                ORDER BY COUNT DESC)
                
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (SELECT MP.MEMBER_ID
                      FROM MEMBER_PROFILE MP
                      JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
                      GROUP BY MP.MEMBER_ID
                      HAVING COUNT(MP.MEMBER_ID) = (SELECT MAX(COUNT)
                                                    FROM REVIEW))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;