-- 코드를 작성해주세요
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES SC
WHERE D.SKILL_CODE & SC.CODE = SC.CODE AND (SC.NAME = 'C#' OR SC.NAME = 'Python')
ORDER BY D.ID;