-- 코드를 작성해주세요
SELECT YEAR(ED1.DIFFERENTIATION_DATE) AS YEAR, MAX_COLONY - ED1.SIZE_OF_COLONY AS YEAR_DEV, ED1.ID
FROM ECOLI_DATA ED1
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) ED2
ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;