-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE F.CATEGORY in ('과자','국','김치','식용유') and(F.CATEGORY, F.PRICE) IN (SELECT F.CATEGORY, MAX(F.PRICE)
                                FROM FOOD_PRODUCT F
                                GROUP BY F.CATEGORY)
ORDER BY F.PRICE DESC;
