-- 코드를 작성해주세요
WITH SKILL_TABLE AS (SELECT ID, NAME AS SKILL_NAME, CATEGORY, EMAIL
                     FROM DEVELOPERS D
                     JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE)

SELECT *
FROM (SELECT (CASE 
              WHEN GROUP_CONCAT(SKILL_NAME) LIKE '%Python%' AND GROUP_CONCAT(CATEGORY) LIKE '%Front End%' THEN 'A'
              WHEN GROUP_CONCAT(SKILL_NAME) LIKE '%C#%' THEN 'B'
              WHEN GROUP_CONCAT(CATEGORY) LIKE '%Front End%' THEN 'C'
              END) AS GRADE, ID, EMAIL
      FROM SKILL_TABLE
      GROUP BY ID, EMAIL) AS GRADE_TABLE
WHERE NOT ISNULL(GRADE)
ORDER BY GRADE ASC, ID ASC;